name: Deploy

on: 
  push: 
    branches: 
      - development
jobs:
    build:
    needs:
      - integrationtests
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v2
     - uses: akhileshns/heroku-deploy@v3.12.12
       with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_email: "geoffreywesthoff@gmail.com"
         heroku_app_name: "skool-development"
         branch: "main"
         procfile: "web: npm start"